# Generated by Django 2.2.12 on 2023-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferenceroom', models.CharField(max_length=20, verbose_name='会议室')),
                ('compereaccount', models.CharField(max_length=20, verbose_name='主持人账号')),
                ('conferencenums', models.CharField(max_length=20, verbose_name='会议人数')),
                ('conferencetitle', models.CharField(max_length=20, verbose_name='会议标题')),
                ('conferenceid', models.CharField(max_length=20, verbose_name='会议编号')),
                ('conferencestatus', models.CharField(max_length=20, verbose_name='会议状态')),
                ('conferencetime', models.DateTimeField(null=True, verbose_name='会议时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompere',
            fields=[
                ('useraccount', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号')),
                ('userpwd', models.CharField(max_length=20, verbose_name='密码')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('conferenceid', models.CharField(max_length=20, verbose_name='会议编号')),
                ('face', models.BinaryField(blank=True, null=True, verbose_name='人脸数据')),
            ],
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraccount', models.CharField(max_length=20, verbose_name='账号')),
                ('userpwd', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
